# Generated by Django 4.2.6 on 2023-11-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0002_alter_news_date_alter_news_news_dislikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytestapp.anonymous')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytestapp.news')),
            ],
        ),
    ]
