# Generated by Django 4.2.6 on 2023-11-02 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0003_anonymous_anonymousfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousfeedback',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
    ]
