# Generated by Django 4.2.6 on 2023-11-02 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0005_anonymousfeedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
